version: '3.4'

services:
  appservice:
    image: ${DOCKER_REGISTRY}appservice
    ports:
      - "8080:80"
    networks:
      - connector
    container_name: appservice
    
  # assignmentprojectservice:
    # image: ${DOCKER_REGISTRY}assignmentprojectservice
    # ports:
      # - "8081:80"
    # networks:
      # - connector
    # container_name: assignmentprojectservice
    
  # authenticationservice:
    # image: ${DOCKER_REGISTRY}authenticationservice
    # ports:
      # - "8082:80"
    # networks:
      # - connector
    # container_name: authenticationservice
    
  configurationservice:
    image: ${DOCKER_REGISTRY}configurationservice
    ports:
      - "8083:80"
    networks:
      - connector
    container_name: configurationservice

  developerprojectservice:
    image: ${DOCKER_REGISTRY}developerprojectservice
    ports:
      - "8084:80"
    networks:
      - connector
    container_name: developerprojectservice
    
  deviceservice:
    image: ${DOCKER_REGISTRY}deviceservice
    ports:
      - "8085:80"
    networks:
      - connector
    container_name: deviceservice
    
  gatewayservice:
    image: ${DOCKER_REGISTRY}gatewayservice
    ports:
      - "8086:80"
    networks:
      - connector
    container_name: gatewayservice
    
  projectservice:
    image: ${DOCKER_REGISTRY}projectservice
    ports:
      - "8087:80"
    networks:
      - connector
    container_name: projectservice
    
  testconstructorservice:
    image: ${DOCKER_REGISTRY}testconstructorservice
    ports:
      - "8088:80"
    networks:
      - connector
    container_name: testconstructorservice
    
  testexecutorservice:
    image: ${DOCKER_REGISTRY}testexecutorservice
    ports:
      - "8089:80"
    networks:
      - connector
    container_name: testexecutorservice
    
  testqueueservice:
    image: ${DOCKER_REGISTRY}testqueueservice
    ports:
      - "8090:80"
    networks:
      - connector
    container_name: testqueueservice
    
  # testresultservice:
    # image: ${DOCKER_REGISTRY}testresultservice
    # ports:
      # - "8091:80"
    # networks:
      # - connector
    # container_name: testresultservice
    
  testservice:
    image: ${DOCKER_REGISTRY}testservice
    ports:
      - "8092:80"
    networks:
      - connector
    container_name: testservice
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - connector
    container_name: mongo
    
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    networks:
      - connector
    container_name: elk
  
networks:
  connector: {}